server:
  port: 8080

spring:
  application:
    name: librarybook-crud-api

  # ===============================
  # DATASOURCE (H2 - LEARNING MODE)
  # ===============================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:librarybookdb
    username: sa
    password: ""

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update   # safe for learning
    show-sql: true       # show SQL in console
    properties:
      hibernate:
        format_sql: true

  # ===============================
  # H2 CONSOLE (DEBUGGING)
  # ===============================
  h2:
    console:
      enabled: true
      path: /h2-console

  # ===============================
  # SPRING MVC
  # ===============================
  mvc:
    problemdetails:
      enabled: true
