spring:
  application:
    name: URLShortener

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/url_shortener
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
